### ISSUE TITLE
mock-data scripts don't work on Windows

### ISSUE THREAD

**Issue by InvokerMaster** [spotify/backstage#1557] opened 2020-07-07 15:24 UTC
Trying to install following the document but wasn't able to create the mock up data.
First of all, thank you for the great product.

**Comment by Rugvip** [comment] 2020-07-07 15:39
Hi, thank you for the report! Could you include the terminal output you're seeing when trying to run `yarn lerna run mock-data`? Will make it easier to troubleshoot.

**Comment by InvokerMaster** [comment] 2020-07-07 15:52
![image](https://user-images.githubusercontent.com/31196185/86807898-4b327e00-c048-11ea-9a21-85be4777d276.png)
It seems like the script is missing.

**Comment by Rugvip** [comment] 2020-07-07 16:01
Assuming that is Windows? Are you executing from PowerShell/CMD or Git Bash/WSL?

**Comment by InvokerMaster** [comment] 2020-07-07 16:03
I am executing from Powershell. Is this an issue. not very familiar with yarn

**Comment by Rugvip** [comment] 2020-07-07 16:05
Yeah we should update the scripts to make that work. In the meantime, are you able to run the scripts through Git Bash or WSL?

**Comment by InvokerMaster** [comment] 2020-07-07 16:08
Ahh. got it. Thank you.

**Comment by amccall-eigt** [comment] 2020-07-07 16:19
I can confirm that the scripts have the same issue running in Git Bash. 

Additionally, running the mock-data script in the @backstage/plugin-scaffolder-backend/scripts folder directly from a git bash context will supply backstage with an unusable file location (pwd command on line 11 resolves to "/c/...filepath.../"). This results in a "NotFoundError: file /c/...filepath.../template.yaml does not exist" coming from the server on the post response.

**Comment by Rugvip** [comment] 2020-07-07 17:37
@amccall-eigt ah yeah ofc, that's not gonna work, thanks :grin:

So yeah, left at this issue needing a fix, and the workaround on Windows right now would be to manually POST the mock-data locations to the catalog with the correct paths.

**Comment by ZaradarDFDS** [comment] 2020-07-08 20:33
Windows gets confused by the missing file extensions on the mock-data scripts in the various packages. If you add the .sh extension to the various mock-data scripts and update the individual package.json files to look like the below it will work:

"mock-data": "./scripts/mock-data.sh"

![mock-data-on-windows](https://user-images.githubusercontent.com/54835628/86967527-081cfb80-c16b-11ea-80c5-fb5a55b141fe.png)

**Comment by ZaradarDFDS** [comment] 2020-07-08 20:34
I realize this would have been better in a pull request but we are literally just getting started on the sprint planning so I have not had time to setup a branch and make a PR. Sorry. :)

**Comment by soapraj** [comment] 2020-08-14 07:45
Once this https://github.com/spotify/backstage/pull/1942 is merged you would not need the mock-data script.

**Comment by mijailr** [comment] 2020-09-09 23:04
Any update to this?

**Comment by freben** [comment] 2020-09-10 05:23
@mijailr The app-config can now contain:

- `catalog.locations` for fixed static locations that shall always be populated. This can be used in production, e.g. for master locations that centrally control the list of software templates available in the org, but it can also be added to an `app-config.development.yaml` so that you get a set of test files registered as part of your dev flow.
- `catalog.exampleEntityLocations`, which is more of a test thing and has a more uncertain future - it was a replacement for basically the scripts mentioned in this ticket, and exists as a small plus sign in the top right of the catalog table when the catalog is empty. Pressing it registers the locations listed in this config key.

example:

```yaml
catalog:
  locations:
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/artist-lookup-component.yaml
  exampleEntityLocations:
    github:
      - https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/artist-lookup-component.yaml
```

**Comment by OrkoHunter** [comment] 2020-09-12 18:57
I believe this can be closed because the mock-data scripts are now removed. https://github.com/spotify/backstage/pull/2439

**Comment by Rugvip** [comment] 2020-09-12 19:17
@OrkoHunter indeed, closing this

**Closed by Rugvip** 2020-09-12 19:17 UTC
Labels: backend, bug, good first issue, help wanted
