### ISSUE TITLE
Linting on license headers on windows machines throws errors and prevents backstage to run.

### ISSUE THREAD

**Issue by carlsim0n** [spotify/backstage#613] opened 2020-04-22 11:42 UTC
## Expected Behavior

```yarn start``` should open the backstage application in my browser window without any errors.

## Current Behavior

Run ```yarn start```
Output in the terminal:
``` bash
Starting the development server...

Failed to compile.

./src/plugins.ts
  Line 16:1:  Missing notice header  `notice/notice
```

Output in the browser window:
```
index.js:1 ./src/plugins.ts
  Line 16:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/App.tsx
  Line 17:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/apis.ts
  Line 17:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/ThemeContext.tsx
  Line 17:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/components/ErrorDisplay/ErrorDisplay.tsx
  Line 17:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/components/Root/Root.tsx
  Line 17:1:  Missing notice header  notice/notice

Search for the keywords to learn more about each error.
console.<computed> @ index.js:1
index.js:1 ./src/components/Root/ToggleThemeSidebarItem.tsx
  Line 17:1:  Missing notice header  notice/notice
```

❗ The error does not exist in this version [v0.1.1-alpha.0](https://github.com/spotify/backstage/releases/tag/v0.1.1-alpha.0) ❗

## Possible Solution

I've tried running backstage on two different mac OS computers without this issue. 
Maybe there's some line ending issues?
Also, it could be a bug inside [eslint-config-oss](https://github.com/spotify/eslint-config-oss)

## Steps to Reproduce

1. Windows 10 machine with
- yarn 1.22.1
- node 12.6.2
2. Open terminal and run:
- ```yarn build```
- ```yarn start```

## Context

Our team wish to be able to develop plugins for backstage without disabling this notice/notice linting rule since it's probably there for a reason.

## Your Environment

- windows 10 (10.0.17134)
- yarn 1.22.1
- node 12.6.2
- google chrome 81.0.4044.113

**Comment by OrkoHunter** [comment] 2020-04-22 12:04
I see that [`spotify/eslint-config-oss`](https://github.com/spotify/eslint-config-oss) is a very lightweight wrapper on [`nickdeis/eslint-plugin-notice`](https://github.com/nickdeis/eslint-plugin-notice). The wrapper is needed to store the [template license notice](https://github.com/spotify/eslint-config-oss/blob/master/notice-template.txt).

So, for some reason, [`nickdeis/eslint-plugin-notice`](https://github.com/nickdeis/eslint-plugin-notice) is unable to find the notice in this environment.

**Comment by OrkoHunter** [comment] 2020-04-22 13:04
@carlsim0n I am trying to reproduce this error on a Windows VM. Meanwhile, you can try running backstage using docker. https://github.com/spotify/backstage/blob/master/docs/getting-started/development-environment.md#optionaltry-on-docker

**Comment by OrkoHunter** [comment] 2020-04-22 13:32
I got this error too on a Windows Server 2019, with yarn 1.22.1 and node v14. :(

<img width="2048" alt="Screen Shot 2020-04-22 at 22 30 06" src="https://user-images.githubusercontent.com/8065913/79987811-d475f200-84e8-11ea-861c-95fae266a48f.png">

**Comment by Rugvip** [comment] 2020-04-22 14:13
This is a regression of https://github.com/spotify/backstage/issues/334, which has a workaround for the issue by setting git config. We shouldn't require git config though, and afaik this fixed the issue last time: https://github.com/spotify/backstage/pull/357

My best guess is that when we switched to the https://github.com/spotify/eslint-config-oss/blob/master/notice-template.txt template, it broke either because of the lack of newline at the end of the file, or the fact that it's a `.txt` instead `.js`. Or it was in fact never working and we need to find a solution :p

**Comment by OrkoHunter** [comment] 2020-04-22 14:20
True, we can fix this by testing in a Windows environment and by making changes to the notice template. I gave up after few attempts as it was taking a lot of time to re-run because of #618 :D

I am having issues with running a windows docker container on macOS. The tutorials asked me to walk on the pathway of vagrant/Virtualbox. I will eventually find courage for this, some other time. 😂

**Comment by Rugvip** [comment] 2020-04-26 23:39
As far as I can tell the issue is that when the template file is downloaded with a package and put in node_modules, the line endings end up always being just LF. That'll trigger the error on windows if the project isn't checked out with LF line endings. Before when we had the template in the repo, it would get checked out with the same line endings as the code, so it would work.

Possible solutions I see would be to move the template back in the repo, ask/fix the notice plugin to ignore line endings, or try to select template based on existing line endings. What do you think @fastfrwrd?

**Comment by fastfrwrd** [comment] 2020-04-27 04:49
Argh! I have no issue with unblocking by moving it back into the repo to
unblock, but let's try to work up something for the eslint plugin, since we
want to use this plugin for all the other Spotify open source projects

**Comment by OrkoHunter** [comment] 2020-04-27 05:10
> since we want to use this plugin for all the other Spotify open source projects

I agree. The plugin can be improved to ignore line endings. (Sounds reasonable too)

**Comment by OrkoHunter** [comment] 2020-04-27 05:42
I raised an issue with the plugin and would love to hear from @nickdeis on this. :)
https://github.com/nickdeis/eslint-plugin-notice/issues/11

**Comment by OrkoHunter** [comment] 2020-04-28 00:43
@nickdeis has pushed a new minor version of `eslint-plugin-notice` with a fix. 🎉 
@Rugvip Can you please check if this issue has been resolved? (I know you can test on windows because of #618) 😁

**Comment by Rugvip** [comment] 2020-04-28 10:18
Yeah looks like it's fixed, but needs https://github.com/spotify/eslint-config-oss/pull/4 to get it into this repo

**Closed** 2020-04-28 17:05 UTC
Labels: bug

**Comment by carlsim0n** [comment] 2020-04-29 09:56
Thank you all for the help! 🍾
