### ISSUE TITLE
ci/cd view: Build status is always completed and green even when it build fails

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#2534] opened 2020-09-21 11:57 UTC
## Expected Behavior
- Status indicator on the each build step is correct colour and status text

## Current Behavior
- When the build fails each build step is listed as `Completed` with a green status mark

## Possible Solution
- Update the status text and colour to reflect a more realistic status

## Steps to Reproduce
- Have a component with builds enabled like the CRA template
- Create a failing build
- Head to the CI/CD tab, and check out the failing build steps

**Comment by rajatdiptabiswas** [comment] 2020-09-21 12:39
Hi @benjdlambert 

I'd like to work on this issue. 
Kindly let me what exactly needs to be done and I'll try my best to get it fixed.

**Comment by timja** [comment] 2020-09-21 13:09
@benjdlambert which plugin? there's at least 3 CI/CD ones hooked up as far as I know, circle, github actions and Jenkins, I think there might be a travis one too

**Comment by benjdlambert** [comment] 2020-09-21 15:14
> @benjdlambert which plugin? there's at least 3 CI/CD ones hooked up as far as I know, circle, github actions and Jenkins, I think there might be a travis one too

sorry, this was a quick ticket that I should have fleshed out a little more. it's the github actions on AFAIK.

**Comment by rajatdiptabiswas** [comment] 2020-09-22 06:42
Hello @benjdlambert 

I have set up the development environment and got the Backstage Example App running on my system.
I am getting overwhelmed by the size of the project. Being new to these is not helping either.

Would you kindly let me know which files I should look into, to make the required fix? 
Any other pointers or suggestions would be highly appreciated.

I have not set up Docker as of yet. Would Docker also be necessary to fix the above problem?

Thanks in advance!

**Comment by benjdlambert** [comment] 2020-09-25 08:17
@shmidt-i could you maybe take a look at @rajatdiptabiswas question? Where does this code come from?

**Comment by shmidt-i** [comment] 2020-09-25 08:52
Of course!

So we are talking about the @backstage/plugin-github-actions package which is located in `plugins/github-actions`. I think mainly there are 2 points of interest - `plugins/github-actions/src/components/WorkflowRunStatus/WorkflowRunStatus.tsx` - there is no failed case atm, but that doesn't give explanation about why they all are just green, cause the default case supposed to be `StatusPending`. The other one is `plugins/github-actions/src/api/GithubActionsClient.ts` - the implementation of the api for the plugin, where you can debug what's the real status is and why it's always shown as a green :)

**Comment by rajatdiptabiswas** [comment] 2020-09-26 05:46
Hi @shmidt-i 

Thanks for the response. 
I'll look into the files and try getting it fixed.

Thanks.

**Comment by rajatdiptabiswas** [comment] 2020-09-26 13:50
Hi @shmidt-i 

I took a look at the files that were related to the screenshots you posted.
Would you kindly tell me the steps necessary to recreate the bug as shown in your screenshot?

I can't seem to understand how to create the failing build with the CRA template.
Would a guest account on the backstage example app be enough to debug this?
It's showing a `Failed to fetch` error on most pages.

I'm very confused and I think it would be best if you looked into the error yourself.
Wish I could be of some more help.

**Comment by benjdlambert** [comment] 2020-09-26 16:16
@rajatdiptabiswas you'll also need to run `yarn start-backend` too to get the backend up and running.

I'd recommend checking out this documentation to get everything running
https://backstage.io/docs/getting-started/running-backstage-locally

And also work through this documentation to get something running
https://backstage.io/docs/features/software-templates/software-templates-index

Then the steps to reproduce might make a little more sense

**Comment by rajatdiptabiswas** [comment] 2020-09-27 13:03
Hi @benjdlambert 

Thanks a lot for the links and `yarn start-backend` command.
The software templates doc has been invaluable.

Please bear with me while I try my best to get this fixed!

**Comment by rajatdiptabiswas** [comment] 2020-09-28 19:37
Hi @benjdlambert 

Fixed the `Failed to fetch` errors, thanks to your `yarn start-backend` tip.

Tried creating components several times using `Create... > Create React App Template` on the website. They took a long time and would eventually fail.

Installed Docker. Tried running `yarn run docker-build:app`, `yarn run docker-build`, `docker run --rm -it -p 7000:7000 -e NODE_ENV=development example-backend:latest`, as well as `docker-compose up`. 

They failed at
```
Backend failed to start up Error: Cannot find module '../schema'
Require stack:
- /usr/src/app/plugins/catalog-graphql/dist/index.cjs.js
- /usr/src/app/plugins/graphql/dist/index.cjs.js
- /usr/src/app/packages/backend/dist/index.cjs.js
...
``` 

Fortunately, trying `Create... > Create React App Template` after the Docker installation helped complete a template build named `testing`.
However, even after creating the template, I could not find the `testing` template on the website. 

Any pointers to help me find the built CRA template and creating the failing build (similar to the screenshots posted by @shmidt-i) would do wonders.

Also tried `yarn add @backstage/plugin-github-actions` and `yarn workspace @backstage/plugin-github-actions start` using https://backstage.io/docs/plugins/ but I'm probably not doing it right.

I tried looking into the docs but I am having trouble fully understanding the docs. 
Really want to get this done, but I'm running into several beginner roadblocks.

Thank you so much for being patient.

**Comment by benjdlambert** [comment] 2020-09-28 21:15
So it looks to me that you're trying to develop on backstage by using a copy of backstage that you made by using `npx @backstage/create-app`? Is that correct?

I think you were on the right track, but we've updated that template that you create by running that command a lot recently with different releases, if you wanting to develop on backstage we recommend you follow this guide https://backstage.io/docs/getting-started/running-backstage-locally to get yourself set up with a clone of the repo rather than something that can drift out of date when we do releaes.

It's not a problem at all, let's see if we can get you set up with a development environment that we can replicate the issue first.

If you follow the guide before, you should be able to do the same commands as before, but I think you'll get past the `schema` issue that you ran in to.

You'll need to create a `Create React App` template with docker installed, and it should successfully create the repo where you choose, and after it's created is where the bug occurs.

Can you try the above and let me know what you see after trying to create a CRA template

**Comment by rajatdiptabiswas** [comment] 2020-09-29 08:58
Hi again @benjdlambert 

I deleted all my previous `git clone` files and started afresh. 
I followed the steps given in https://backstage.io/docs/getting-started/running-backstage-locally.

Once the Example App was running, I logged in as `Guest` and created a new template using `Create... > Create React App` from the website.

`RUN THE TEMPLATER` completed successfully with the following message.
```
...
Done in 323.29s.
Success! Created backstage-test at /result/backstage-test

Inside that directory, you can run several commands:
yarn start
...

We suggest that you begin by typing:
cd backstage-test
yarn start

Happy hacking!
```
`backstage-test` was the template name I used when creating the template. I can't seem to find the `backstage-test` directory.

However `PUBLISH TEMPLATE` ran into this error.
```
error: Stage failed with error: No publisher registered for type: "github" {"id":"0ebc71e1-c6fc-4a3e-b2c8-1ccb72ebe40a","stage":"Publish template","timestamp":"2020-09-29T07:25:15.505Z"}
```
I ran into the above error several times yesterday as well.

I'm guessing I made a mistake while putting the repo name they ask for when creating the template? 
Or do I need to complete the GitHub OAuth process following the steps given in https://github.com/spotify/backstage/tree/master/plugins/auth-backend#github?

Thanks once again.

**Comment by benjdlambert** [comment] 2020-09-29 11:44
Yeah you'll net to get setup with a Personal Access token to be able to create the repositories in Github.

Take a look at these docs to get the scaffolder set up correctly.
https://backstage.io/docs/features/software-templates/installation

**Comment by rajatdiptabiswas** [comment] 2020-09-29 18:52
Tried a few of the steps in the documentation. Still no luck. 
Will get back to this, first thing tomorrow morning with a clear head.

I shall let you know as soon as I manage to get it running.

**Comment by benjdlambert** [comment] 2020-09-30 07:43
Ok it's mainly the part that looks like this in the documentation:
```

  const githubClient = new Octokit({ auth: githubToken });
  const githubPublisher = new GithubPublisher({
    client: githubClient,
    token: githubToken,
    repoVisibility,
  });
  publishers.register('file', githubPublisher);
```

**Comment by rajatdiptabiswas** [comment] 2020-09-30 08:19
Hi @benjdlambert 

There's another problem that I ran into. Decided to start afresh again and follow each step diligently.

Followed the steps in `Running Backstage Locally`. Also set the environment variables for `AUTH_GITHUB_CLIENT_ID` and `AUTH_GITHUB_CLIENT_SECRET`.

Then moved onto trying to install the Scaffolder plugin as you mentioned earlier. The documentation stated that `The Scaffolder plugin also depends on the Software Catalog`. Hence looked up the documentation for installing `@backstage/plugin-catalog` and `@backstage/plugin-catalog-backend` as well.

While following the steps there, I ran into an issue. 
There is a step, in the docs, which mentions to add a few lines inside the `ApiRegistry` builder function in `packages/app/src/apis.ts`. However `apis.ts` does not seem to have the builder function.
A reference to a `ApiRegistry` builder function could be found in `packages/storybook/.storybook/apis.js` but that is probably not what we are looking for.

It's not just the Software Catalog plugin installation docs. The Scaffolder documentation also requires adding a `builder.add(...)` inside the `ApiRegistry` builder function of `packages/app/src/apis.ts`.

Should I just use `npx @backstage/create-app` instead? The docs state that the plugins will already be present if I used that command.

I'm really sorry for being such a headache.
Thanks for all your support!

**Comment by benjdlambert** [comment] 2020-09-30 09:45
If you clone the main repo this stuff should already be setup in the example backend package that we ship the development. You should be able to just add a github access token to config and create components? Are you not seeing that?

**Comment by rajatdiptabiswas** [comment] 2020-09-30 11:14
I just noticed that `@backstage/plugin-catalog`, `@backstage/plugin-catalog-backend`, `@backstage/plugin-scaffolder`, and `@backstage/plugin-scaffolder-backend` were already present in their respective `package.json`. 
I'm sorry for not noticing those earlier.

Setting up the `GITHUB_ACCESS_TOKEN` environment variable fixed the following warning when running `yarn start` from `backstage/packages/backend`.
```
2020-09-30T07:53:15.521Z scaffolder warn Skipping github scaffolding provider, Missing required config value at 'scaffolder.github.token'
```

It would have been easier if the docs mentioned to simply set up the `GITHUB_ACCESS_TOKEN` variable.

I was able to sign in with GitHub as well. The GitHub request access page showed up and I granted access to the `backstage-dev` OAuth App I created earlier.

However, after the sign in `http://localhost:3000/create` is not loading like it used to. It's just a white screen now.
I'll redo everything and check whether the issue goes away.

This is taking way longer than it should. Thanks for the patience.

**Comment by rajatdiptabiswas** [comment] 2020-09-30 12:42
Hi @benjdlambert 

I finally got a repo made. The component is showing up under `Home > Websites`. However the `CI/CD` tab shows the following.
```
CI/CD switcher:
No CI/CD is available for this entity. Check corresponding annotations!
```

This was a long time coming, but at least I just got the setup done!

**Comment by benjdlambert** [comment] 2020-09-30 12:57
Ok perfect! Let me check this and get back to you, I think if you're using a fork of the repo the annotations should be up to date, @shmidt-i or was this work not merged yet, could we get that work merged if possible and leave the other changes in a seperate PR/

**Comment by rajatdiptabiswas** [comment] 2020-09-30 13:03
@benjdlambert I did not fork the repo. 
I used `git clone git@github.com:spotify/backstage.git` to clone the repository onto my system. 
Followed the documentation steps as is.

**Comment by benjdlambert** [comment] 2020-09-30 13:53
ok I think the annotations are not merged yet, so you might not get the github for free with CRA, can you try the SSR template and see if that works?

**Comment by rajatdiptabiswas** [comment] 2020-10-01 07:52
@benjdlambert Managed to get it running using the React SSR template.

The build is showing as failed on my `Actions` tab on GitHub, but showing completed and green in the Backstage Example App.
I got similar error logs to the screenshots posted by @shmidt-i.

I'll try to figure out what might be causing them.

**Comment by benjdlambert** [comment] 2020-10-01 07:57
@rajatdiptabiswas perfect! apologies it's been a ride to try get to this point but now we have something!

**Comment by erictnilsson** [comment] 2020-10-01 19:09
Hi!
I'm not sure if this is some sort of faux pas in the open source community (i'm new to this) since the issue is already assigned to @rajatdiptabiswas , but I took a look at the issue and seem to have found the root cause. Please, let me know if that's the case; I don't want to step on any toes :)

From what I've gathered, the Github check-run api returns among other things both a `status` and a `conclusion`. [According to the Github API docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#create-a-check-run), the `status` can only be one of `queued`, `in_progress`, or `complete` whereas the `conclusion` is the final conclusion of the check (a status of `completed`). `Conclusion` can be one of `success`, `failure`, `neutral`, `cancelled`, `skipped`, `timed_out`, or `action_required`. [The v3 docs has a nice little visualization of this:](https://developer.github.com/v3/checks/runs/)
<img width="608" alt="Screenshot 2020-10-01 at 21 00 45" src="https://user-images.githubusercontent.com/16206098/94851766-2e300000-0429-11eb-8260-9164e554e141.png">
When debugging, it is evident that the actual `conclusion` of the builds is set as "failure" while the `status` is "complete". 
This means that the `status` doesn't represent whether the build has failed or not, only that it's been completed. Since the `conclusion` isn't accounted for in _WorkflowRunStatus.tsx_, the build status stays a friendly green since it's completed even it if it in actuality failed. 

I can see a couple of potential fixes for this, some bigger than others. I'd be happy to hear your thoughts on what I found and I'd be even more happy to correct it!

**Comment by rajatdiptabiswas** [comment] 2020-10-01 20:02
Hi @erictnilsson 

It's amazing that you found the root cause of the issue this quick. 
Your comment is very comprehensive as well.

I'm even newer to all this (as evident by the amount of time I took to just recreate the bug).
You're definitely more qualified to fix this! I think it's best you take it from here.

Good luck!

**Comment by erictnilsson** [comment] 2020-10-02 13:21
Thank you @rajatdiptabiswas! 
Do you guys have any preferred solution in mind @benjdlambert or should I brainstorm a few of my ideas? :)

**Closed** 2020-10-07 11:15 UTC
Labels: Hacktoberfest, bug, good first issue
