### ISSUE TITLE
Error: Cannot find module 'lodash/fp'

### ISSUE THREAD

**Issue by bih** [spotify/backstage#1568] opened 2020-07-08 15:30 UTC
## Expected Behavior

With no code changes to the `packages/cli` repository, the CLI workflow in CI/CD should pass.

## Current Behavior

When making a non-code change to `packages/cli`, the CLI workflow (based in `.github/workflows/cli.yml` - also possibly `cli-win.yml`?) fails with the following console output:

```
2020-07-08T15:17:18.2270138Z Building dist workspace
2020-07-08T15:17:18.2273924Z Preparing workspace
2020-07-08T15:17:29.4978810Z Pinning yarn version in workspace
2020-07-08T15:17:29.5006219Z Installing workspace dependencies
2020-07-08T15:17:50.8919996Z Creating a Backstage App
2020-07-08T15:17:51.2719041Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required]
2020-07-08T15:17:51.2726195Z [node backstage-cli create-app --skip-install].out: [38D[38C
2020-07-08T15:17:51.2980716Z Waiting for app create script to be done
2020-07-08T15:17:51.2996659Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.2997430Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] t
2020-07-08T15:17:51.3024060Z [node backstage-cli create-app --skip-install].out: [39D
2020-07-08T15:17:51.3024571Z [node backstage-cli create-app --skip-install].out: [39C
2020-07-08T15:17:51.3025019Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3025558Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] te
2020-07-08T15:17:51.3026005Z [node backstage-cli create-app --skip-install].out: [40D
2020-07-08T15:17:51.3026437Z [node backstage-cli create-app --skip-install].out: [40C
2020-07-08T15:17:51.3026880Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3027411Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] tes
2020-07-08T15:17:51.3027954Z [node backstage-cli create-app --skip-install].out: [41D[41C
2020-07-08T15:17:51.3028392Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3028987Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] test
2020-07-08T15:17:51.3029453Z [node backstage-cli create-app --skip-install].out: [42D[42C
2020-07-08T15:17:51.3030235Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3030780Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] test-
2020-07-08T15:17:51.3031242Z [node backstage-cli create-app --skip-install].out: [43D[43C
2020-07-08T15:17:51.3031680Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3032282Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] test-a[44D[44C
2020-07-08T15:17:51.3032866Z [node backstage-cli create-app --skip-install].out: [2K[G? Enter a name for the app [required] test-ap
2020-07-08T15:17:51.3033342Z [node backstage-cli create-app --skip-install].out: [45D[45C[2K[G
2020-07-08T15:17:51.3039861Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] test-app[46D[46C
2020-07-08T15:17:51.3040517Z [node backstage-cli create-app --skip-install].out: [2K[G
2020-07-08T15:17:51.3041126Z [node backstage-cli create-app --skip-install].out: ? Enter a name for the app [required] test-app[46D[46C
2020-07-08T15:17:51.3041559Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3056517Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3057026Z [node backstage-cli create-app --skip-install].out: Creating the app...
2020-07-08T15:17:51.3057686Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3058317Z [node backstage-cli create-app --skip-install].out:  Checking if the directory is available:
2020-07-08T15:17:51.3087764Z [node backstage-cli create-app --skip-install].err:   checking      test-app ✔
2020-07-08T15:17:51.3088308Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3089426Z [node backstage-cli create-app --skip-install].out:  Creating a temporary app directory:
2020-07-08T15:17:51.3092781Z [node backstage-cli create-app --skip-install].err:   creating      temporary directory ✔
2020-07-08T15:17:51.3093346Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3094294Z [node backstage-cli create-app --skip-install].out:  Preparing files:
2020-07-08T15:17:51.3154523Z [node backstage-cli create-app --skip-install].err:   copying       .eslintrc.js ✔
2020-07-08T15:17:51.3165221Z [node backstage-cli create-app --skip-install].err:   copying       README.md ✔
2020-07-08T15:17:51.3170057Z [node backstage-cli create-app --skip-install].err:   copying       app-config.yaml ✔
2020-07-08T15:17:51.3174274Z [node backstage-cli create-app --skip-install].err:   copying       lerna.json ✔
2020-07-08T15:17:51.3281067Z [node backstage-cli create-app --skip-install].err:   templating    package.json.hbs ✔
2020-07-08T15:17:51.3286575Z [node backstage-cli create-app --skip-install].err:   copying       tsconfig.json ✔
2020-07-08T15:17:51.3293105Z [node backstage-cli create-app --skip-install].err:   copying       .eslintrc.js ✔
2020-07-08T15:17:51.3298632Z [node backstage-cli create-app --skip-install].err:   copying       cypress.json ✔
2020-07-08T15:17:51.3326228Z [node backstage-cli create-app --skip-install].err:   templating    package.json.hbs ✔
2020-07-08T15:17:51.3332068Z [node backstage-cli create-app --skip-install].err:   copying       android-chrome-192x192.png ✔
2020-07-08T15:17:51.3337734Z [node backstage-cli create-app --skip-install].err:   copying       apple-touch-icon.png ✔
2020-07-08T15:17:51.3342885Z [node backstage-cli create-app --skip-install].err:   copying       favicon-16x16.png ✔
2020-07-08T15:17:51.3348300Z [node backstage-cli create-app --skip-install].err:   copying       favicon-32x32.png ✔
2020-07-08T15:17:51.3353369Z [node backstage-cli create-app --skip-install].err:   copying       favicon.ico ✔
2020-07-08T15:17:51.3358866Z [node backstage-cli create-app --skip-install].err:   copying       index.html ✔
2020-07-08T15:17:51.3363717Z [node backstage-cli create-app --skip-install].err:   copying       manifest.json ✔
2020-07-08T15:17:51.3369296Z [node backstage-cli create-app --skip-install].err:   copying       robots.txt ✔
2020-07-08T15:17:51.3374410Z [node backstage-cli create-app --skip-install].err:   copying       safari-pinned-tab.svg ✔
2020-07-08T15:17:51.3380590Z [node backstage-cli create-app --skip-install].err:   copying       App.test.tsx ✔
2020-07-08T15:17:51.3385960Z [node backstage-cli create-app --skip-install].err:   copying       App.tsx ✔
2020-07-08T15:17:51.3390914Z [node backstage-cli create-app --skip-install].err:   copying       index.tsx ✔
2020-07-08T15:17:51.3396207Z [node backstage-cli create-app --skip-install].err:   copying       plugins.ts ✔
2020-07-08T15:17:51.3401110Z [node backstage-cli create-app --skip-install].err:   copying       setupTests.ts ✔
2020-07-08T15:17:51.3406370Z [node backstage-cli create-app --skip-install].err:   copying       .eslintrc.json ✔
2020-07-08T15:17:51.3411204Z [node backstage-cli create-app --skip-install].err:   copying       app.js ✔
2020-07-08T15:17:51.3417207Z [node backstage-cli create-app --skip-install].err:   copying       .eslintrc.js ✔
2020-07-08T15:17:51.3422225Z [node backstage-cli create-app --skip-install].err:   copying       README.md ✔
2020-07-08T15:17:51.3445597Z [node backstage-cli create-app --skip-install].err:   templating    package.json.hbs ✔
2020-07-08T15:17:51.3450328Z [node backstage-cli create-app --skip-install].err:   copying       index.tsx ✔
2020-07-08T15:17:51.3455121Z [node backstage-cli create-app --skip-install].err:   copying       index.ts ✔
2020-07-08T15:17:51.3459958Z [node backstage-cli create-app --skip-install].err:   copying       plugin.test.ts ✔
2020-07-08T15:17:51.3464144Z [node backstage-cli create-app --skip-install].err:   copying       plugin.ts ✔
2020-07-08T15:17:51.3468799Z [node backstage-cli create-app --skip-install].err:   copying       setupTests.ts ✔
2020-07-08T15:17:51.3473990Z [node backstage-cli create-app --skip-install].err:   copying       Timer.tsx ✔
2020-07-08T15:17:51.3478217Z [node backstage-cli create-app --skip-install].err:   copying       index.ts ✔
2020-07-08T15:17:51.3482785Z [node backstage-cli create-app --skip-install].err:   copying       WelcomePage.test.tsx ✔
2020-07-08T15:17:51.3487889Z [node backstage-cli create-app --skip-install].err:   copying       WelcomePage.tsx ✔
2020-07-08T15:17:51.3492169Z [node backstage-cli create-app --skip-install].err:   copying       index.ts ✔
2020-07-08T15:17:51.3492730Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3493928Z [node backstage-cli create-app --skip-install].out:  Moving to final location:
2020-07-08T15:17:51.3515346Z [node backstage-cli create-app --skip-install].err:   moving        test-app ✔
2020-07-08T15:17:51.3516556Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3517519Z [node backstage-cli create-app --skip-install].out: 🥇  Successfully created test-app
2020-07-08T15:17:51.3521451Z [node backstage-cli create-app --skip-install].out: 
2020-07-08T15:17:51.3564881Z Child finished
2020-07-08T15:17:51.3566553Z Rewriting module resolutions of app to use workspace packages
2020-07-08T15:17:51.3586006Z Pinning yarn version and registry in app
2020-07-08T15:17:51.3596616Z Test app created
2020-07-08T15:17:51.3597525Z Running 'yarn install' in newly created app
2020-07-08T15:18:58.7064159Z Running 'yarn tsc' in newly created app
2020-07-08T15:19:09.1761538Z Running 'yarn build' in newly created app
2020-07-08T15:19:11.8002821Z Running 'yarn lint:all' in newly created app
2020-07-08T15:19:17.5106922Z Running 'yarn test:all' in newly created app
2020-07-08T15:19:43.1525351Z Running 'yarn test:e2e:ci' in newly created app
2020-07-08T15:19:44.0857244Z internal/modules/cjs/loader.js:969
2020-07-08T15:19:44.0857995Z   throw err;
2020-07-08T15:19:44.0858385Z   ^
2020-07-08T15:19:44.0858663Z 
2020-07-08T15:19:44.0859804Z Error: Cannot find module 'lodash/fp'
2020-07-08T15:19:44.0860342Z Require stack:
2020-07-08T15:19:44.0861145Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js
2020-07-08T15:19:44.0862447Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/index.js
2020-07-08T15:19:44.0863792Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/bin/start.js
2020-07-08T15:19:44.0864178Z Error: Error: Command failed: yarn test:e2e:ci
2020-07-08T15:19:44.0868297Z internal/modules/cjs/loader.js:969
2020-07-08T15:19:44.0868919Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2020-07-08T15:19:44.0869158Z   throw err;
2020-07-08T15:19:44.0881242Z     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2020-07-08T15:19:44.0881445Z   ^
2020-07-08T15:19:44.0883059Z     at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-07-08T15:19:44.0883173Z 
2020-07-08T15:19:44.0895778Z     at require (internal/modules/cjs/helpers.js:72:18)
2020-07-08T15:19:44.0896380Z Error: Cannot find module 'lodash/fp'
2020-07-08T15:19:44.0896969Z     at Object.<anonymous> (/tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js:8:72)
2020-07-08T15:19:44.0897235Z     at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-07-08T15:19:44.0897450Z Require stack:
2020-07-08T15:19:44.0897702Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-07-08T15:19:44.0898218Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js
2020-07-08T15:19:44.0898469Z     at Module.load (internal/modules/cjs/loader.js:986:32)
2020-07-08T15:19:44.0899239Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/index.js
2020-07-08T15:19:44.0899555Z     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-07-08T15:19:44.0899788Z     at Module.require (internal/modules/cjs/loader.js:1026:19) {
2020-07-08T15:19:44.0900175Z   code: 'MODULE_NOT_FOUND',
2020-07-08T15:19:44.0900346Z   requireStack: [
2020-07-08T15:19:44.0900758Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js',
2020-07-08T15:19:44.0901211Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/index.js',
2020-07-08T15:19:44.0901687Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/bin/start.js'
2020-07-08T15:19:44.0901860Z   ]
2020-07-08T15:19:44.0902016Z }
2020-07-08T15:19:44.0902236Z error Command failed with exit code 1.
2020-07-08T15:19:44.0902763Z - /tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/bin/start.js
2020-07-08T15:19:44.0903039Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2020-07-08T15:19:44.0903282Z     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2020-07-08T15:19:44.0903509Z     at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-07-08T15:19:44.0903722Z     at require (internal/modules/cjs/helpers.js:72:18)
2020-07-08T15:19:44.0904211Z     at Object.<anonymous> (/tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js:8:72)
2020-07-08T15:19:44.0904448Z     at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-07-08T15:19:44.0904694Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-07-08T15:19:44.0904922Z     at Module.load (internal/modules/cjs/loader.js:986:32)
2020-07-08T15:19:44.0905149Z     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-07-08T15:19:44.0905379Z     at Module.require (internal/modules/cjs/loader.js:1026:19) {
2020-07-08T15:19:44.0905718Z   code: 'MODULE_NOT_FOUND',
2020-07-08T15:19:44.0905889Z   requireStack: [
2020-07-08T15:19:44.0906300Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/wait-on/lib/wait-on.js',
2020-07-08T15:19:44.0906746Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/index.js',
2020-07-08T15:19:44.0907207Z     '/tmp/backstage-e2e-aFyAzM/test-app/node_modules/start-server-and-test/src/bin/start.js'
2020-07-08T15:19:44.0907379Z   ]
2020-07-08T15:19:44.0907505Z }
2020-07-08T15:19:44.0907746Z error Command failed with exit code 1.
2020-07-08T15:19:44.0907970Z 
2020-07-08T15:19:44.0908180Z     at ChildProcess.exithandler (child_process.js:303:12)
2020-07-08T15:19:44.0908387Z     at ChildProcess.emit (events.js:315:20)
2020-07-08T15:19:44.0908594Z     at maybeClose (internal/child_process.js:1021:16)
2020-07-08T15:19:44.0908825Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-07-08T15:19:44.0943821Z ##[error]Process completed with exit code 1.
```

See our [test pull request](https://github.com/spotify/backstage/pull/1567) (#1567) that demonstrates it in action.

## Possible Solution

Something to do with `lodash/fp`. Maybe an outdated dependency.

## Steps to Reproduce

1. `git clone git@github.com:spotify/backstage.git`
2. `git checkout -b test-pull-request`
3. `yarn install`
4. `yarn tsc`
5. `touch packages/cli/TEST_FILE_TO_INVOKE_CLI_WORKFLOW_IN_GITHUB_ACTIONS.txt`
6. `git commit -am "commit"`
7. `git push -u origin HEAD`
8. Wait for pull request's CI (via GitHub actions) to resolve. The CLI and CLI Windows CI builds will fail with the error above.

## Context

This is blocking our work on merging #1564 which also has the same issue, which in turn is impacting our delivery on shipping the TechDocs CLI and the v0 release.

## Your Environment

- NodeJS Version (v12): v12.13.1
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS X 10.15.4
- Browser Information: Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by Rugvip** [comment] 2020-07-08 16:55
Couldn't reproduce with `node packages/cli/e2e-test/cli-e2e-test.js` so tried retriggering of the test PR, and it was fine too. This was probably a bad package version in NPM that someone then fixed.

The CLI e2e tests is essentially an NPM e2e test too, in that it pulls down the latest packages from NPM as if you're running a fresh install. No need to block merging of PRs on that if everything else seems fine.

**Comment by benjdlambert** [comment] 2020-07-09 13:10
Think this should be fixed now @bih? Will close this issue and re-open if it's still causing issues.

**Closed by benjdlambert** 2020-07-09 13:10 UTC
Labels: bug
