### ISSUE TITLE
Add Search bar to easily find components by name

### ISSUE THREAD

**Issue by murtadha** [spotify/backstage#1235] opened 2020-06-10 23:11 UTC
## Feature Suggestion

We want to be able to search for components by name (and maybe other fields: tags, descriptions, etc).

## Possible Implementation

This can be a simple front end search that does basic string matching on the available components and only shows ones matching the result

It's possible to implement something more complex, with a typeahead and server-side computations, but that might be less necessary to start with

**Comment by stefanalund** [comment] 2020-06-11 08:26
The service catalog table view already have basic Search integrated:

![Screenshot 2020-06-11 at 09 29 42](https://user-images.githubusercontent.com/190856/84357547-202e4900-abc6-11ea-8c8b-b40225d5dd91.png)

We have prepared a placeholder for site wide search in the sidebar:

![Screenshot 2020-06-11 at 09 25 13](https://user-images.githubusercontent.com/190856/84357678-5e2b6d00-abc6-11ea-81b2-ae3cccf628ce.png)

**Comment by stefanalund** [comment] 2020-08-10 10:10
Duplicate of #1499

**Closed by stefanalund** 2020-08-10 10:10 UTC
Labels: help wanted
