### ISSUE TITLE
TechDocs: Docs Not Found 

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#1750] opened 2020-07-27 07:54 UTC
Currenlty, this is what the [TechDocs Not Found](https://github.com/spotify/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsNotFound.tsx) page looks like. 
<img width="1436" alt="Screen Shot 2020-07-27 at 9 34 11 AM" src="https://user-images.githubusercontent.com/25153114/88515718-6f9ccd00-cfec-11ea-8373-93c6f4bc7316.png">

To be consistent throughout Backstage we would like to use the [ErrorPage](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/ErrorPage/ErrorPage.tsx) component
![image](https://user-images.githubusercontent.com/25153114/88515907-b7bbef80-cfec-11ea-81f2-b1117a7253cc.png)

* Render the ErrorPage component in TechDocsNotFound
* Make the ErrorPage component customizable so that for example:
          - "Error 404: Page not found" is "Error 404: Documentation not found" 
          -  The path that the user visited is visible as something like "Path: /docs/..." 

Feel free to suggest any other improvements!

**Comment by DavidJSykes** [comment] 2020-07-27 12:16
I was attempting to solve this issue, and for the life of me, I can't get the Typography element for ErrorPage to accept a newline character.  If anyone know's how to do that I would love to know!

**Comment by OrkoHunter** [comment] 2020-07-27 13:52
Hi @DavidJSykes ! In my understanding -

```jsx
<Typography>
Line 1
<br />
Line2
</Typography>
```

This way we can insert newline inside a Material UI Typography element. :)

**Comment by emmaindal** [comment] 2020-07-27 14:44
@DavidJSykes fantastic, thank you! I'll assign it to you then 😄

**Comment by DavidJSykes** [comment] 2020-07-29 12:36
@OrkoHunter thank you for that, I was trying to get the existing ErrorPage to accept it as a parameter, and unfortunately, it just will not play ball.

**Comment by DavidJSykes** [comment] 2020-07-29 14:15
@emmaindal I have been hitting monorepo/no-internal-import or other similar issues trying to use the existing ErrorPage. Other than making the TechDocsNotFound almost a duplicate of the ErrorPage I'm not sure I could fix this.

**Comment by hooloovooo** [comment] 2020-07-30 08:06
@DavidJSykes I'm not entirely sure how you're doing it, but i'm guessing you are trying to import ErrorPage using a relative path instead of @backstage/core. Could you try using `import { ErrorPage } from '@backstage/core'`? Feel free to tag me as well if it doesn't work and/or you need any more help. @emmaindal is on vacation this week.

**Comment by emmaindal** [comment] 2020-07-30 09:17
@DavidJSykes and @hooloovooo I don't think the ErrorPage component is exported from backstage core yet, so you may have to export it from [here](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/index.ts).

**Comment by DavidJSykes** [comment] 2020-07-30 09:29
@emmaindal and @hooloovooo thank you guys I was so close! I had already set up exporting in the right place, but I was importing it incorrectly. I'll give it another go now.

**Comment by DavidJSykes** [comment] 2020-07-30 11:28
@hooloovooo Is there any chance you could shed a bit of light on this error message the test suite is giving me?
![static config error](https://user-images.githubusercontent.com/20754213/88916654-5c913380-d25e-11ea-837a-e8a6edc5ef6b.png)

**Comment by hooloovooo** [comment] 2020-07-30 11:36
@DavidJSykes Not sure about that one. Looks like something unrelated to what you're working on. Could be a windows specific bug in Backstage. Could you upload a fork somewhere where i can have a look?

**Comment by DavidJSykes** [comment] 2020-07-30 11:41
https://github.com/DavidJSykes/backstage/tree/Fix-TechDocs-missing

**Comment by hooloovooo** [comment] 2020-07-30 11:49
@DavidJSykes Seems like that should work, and it does for me. What version of node are you running?

**Comment by DavidJSykes** [comment] 2020-07-30 11:50
@hooloovooo I'm using 12.18.3 did you run the tests in a Linux environment?

**Comment by hooloovooo** [comment] 2020-07-30 11:53
> @hooloovooo I'm using 12.18.3 did you run the tests in a Linux environment?

I did. Trying in windows now.

**Comment by hooloovooo** [comment] 2020-07-30 12:47
@DavidJSykes I'm getting all kinds of issues trying to run the tests on windows. Seems a lot of them aren't compatible. If you're writing tests for your stuff, could you just run those specifically and make sure they work. We'll run all the other tests to make sure there are no regressions in the pull request.

**Comment by DavidJSykes** [comment] 2020-07-30 13:03
@hooloovooo I set it all up on my macbook and it does now seem to run the tests. Did the code look alright otherwise?

**Comment by hooloovooo** [comment] 2020-07-30 13:10
@DavidJSykes I didn't look too closely, but if you feel happy with what you've got or want a place to discuss specifics feel free to create a PR. :)

**Comment by Rugvip** [comment] 2020-07-30 14:23
Tracking the windows issue here: https://github.com/spotify/backstage/issues/1788. Work around it by running only the specific tests you need for now : /

**Closed** 2020-07-30 17:32 UTC
Labels: docs-like-code, good first issue, help wanted
