### ISSUE TITLE
Can no longer override public path

### ISSUE THREAD

**Issue by Pajn** [spotify/backstage#1106] opened 2020-06-02 08:19 UTC
In an older version we did set the `PUBLIC_URL` environment variable when building but after upgrading to alpha.6 it seems like that no longer works. I might have missed another option for it somewhere but from https://github.com/spotify/backstage/blob/9db24c79b80625626df5d09c93f12b083462b451/packages/cli/src/lib/bundler/config.ts#L82 it looks hardcoded.

## Expected Behavior

There should be a way to override webpacks publicPath so that the application can be hosted in a subfolder

## Current Behavior

It's no longer possible so when hosting in a subfolder, all assets all stilled pulled from `/`

## Possible Solution

Allow an environment variable to override the publicPath in the webpack config here: https://github.com/spotify/backstage/blob/9db24c79b80625626df5d09c93f12b083462b451/packages/cli/src/lib/bundler/config.ts#L82

## Steps to Reproduce

N/A

## Context

I think the general description covers it

## Your Environment

- NodeJS Version (v12): v12.16.3
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Firefox but N/A

**Comment by Rugvip** [comment] 2020-06-02 08:22
Thanks for reporting! Closing this as a duplicate of #1033, please continue the discussion there.

**Closed by Rugvip** 2020-06-02 08:22 UTC
Labels: bug
