### ISSUE TITLE
backstage app is opening but i am not able to sign in through github getting error 

### ISSUE THREAD

**Issue by anshika-cs** [spotify/backstage#1618] opened 2020-07-14 11:43 UTC
## Expected Behavior

![gitissue](https://user-images.githubusercontent.com/68241261/87421880-48f69380-c5f5-11ea-91d7-7f5f5570fb21.JPG)
NotFoundError: No environment for development found in this provider at EnvironmentHandler.getProviderForEnv (webpack-internal:///../../plugins/auth-backend/src/lib/EnvironmentHandler.ts:34:13) at EnvironmentHandler.start (webpack-internal:///../../plugins/auth-backend/src/lib/EnvironmentHandler.ts:42:27) at handleReturn (C:\Users\devNXT\source\repos\backstage2\node_modules\express-promise-router\lib\express-promise-router.js:24:27) at C:\Users\devNXT\source\repos\backstage2\node_modules\express-promise-router\lib\express-promise-router.js:56:9 at handleReturn (C:\Users\devNXT\source\repos\backstage2\node_modules\express-promise-router\lib\express-promise-router.js:24:27) at C:\Users\devNXT\source\repos\backstage2\node_modules\express-promise-router\lib\express-promise-router.js:56:9 at Layer.handle [as handle_request] (C:\Users\devNXT\source\repos\backstage2\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\devNXT\source\repos\backstage2\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\Users\devNXT\source\repos\backstage2\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\Users\devNXT\source\repos\backstage2\node_modules\express\lib\router\layer.js:95:5)

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment] 2020-07-14 15:44
Duplicate of #1622

**Closed by benjdlambert** 2020-07-14 15:44 UTC
Labels: bug
